https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

Importing pandas

In [1]:
import pandas as pd

Opening a local csv file

In [5]:
df = pd.read_csv('data.csv')

Reading CSV from the url

In [11]:
# import requests
# from io import StringIO


# url="https://github.com/plotly/datasets/blob/master/data.csv"
# headers={"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
# req= requests.get(url, headers=headers)
# data=StringIO(req.text)
# print(data)
# # df2 = pd.read_csv(data)

# this doesnot work it works on the ://githubusercontent.com

df2 = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/refs/heads/master/data.csv")
df2.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

Sep Parameter

In [ ]:
pd.read_csv('data1.tsv',sep='\t')  # default sep is comma with \t we can use the tab separated file

,id,name,email,phone,address,company,website,description,timestamp,random_number
0,482197,Mrs. Crystel Kilback,stehr.ron@mitchell.org,(331) 883-0638,"26136 Rogahn Shores North Jeradchester, CO 410...","Bednar, Parisian and Heathcote",https://examplefile.com,Sample file from ExampleFile.com,2022-09-06T23:49:30+0000,19400
1,483618,Edna Konopelski,justina85@hotmail.com,+1-915-716-6309,"31229 Pfeffer Coves Apt. 123 Maximechester, ND...",Okuneva-Greenfelder,https://examplefile.com,Sample file from ExampleFile.com,1988-09-07T12:28:15+0000,64541
2,169389,Evalyn Spinka,jermey68@cruickshank.com,478.519.0099,70676 Gilbert Ferry Suite 568 Lake Antonettest...,Carroll LLC,https://examplefile.com,Sample file from ExampleFile.com,2006-05-13T04:42:01+0000,17803
3,137571,Lula Conn,anabel.klein@hotmail.com,+18643331243,"67821 Dare Alley Apt. 382 South Meredithmouth,...",Armstrong LLC,https://examplefile.com,Sample file from ExampleFile.com,1995-12-30T23:33:48+0000,12670
4,883214,Benton Sanford IV,dmitchell@gmail.com,1-269-634-6153,"919 Jadyn Route Suite 681 Carminefort, VT 4697...",Funk Inc,https://examplefile.com,Sample file from ExampleFile.com,1998-08-14T21:54:21+0000,2764
5,71315,Dr. Immanuel Mayer,claud.russel@treutel.com,+1-512-514-6693,"9670 Mills Landing Gutkowskihaven, DE 82483","Bergnaum, Sipes and Hoeger",https://examplefile.com,Sample file from ExampleFile.com,1974-12-12T07:14:52+0000,48902
6,739940,Ms. Crystel Cummings,aankunding@hotmail.com,+1 (631) 903-5562,"33511 Christa Trail Lake Jada, KS 52270",Hagenes-Wilderman,https://examplefile.com,Sample file from ExampleFile.com,1987-09-09T01:04:12+0000,40513
7,425524,Ms. Monica Roberts,kristian42@batz.com,+1 (669) 438-4452,"65892 Octavia Circle Suite 792 Jacintostad, MI...",Hamill-Kemmer,https://examplefile.com,Sample file from ExampleFile.com,2020-03-29T22:47:12+0000,59996
8,637305,Elwin Langosh,sauer.mohamed@hotmail.com,240.954.5678,"838 Renner Crossing Apt. 510 East Archibald, I...","Rogahn, Bashirian and Schulist",https://examplefile.com,Sample file from ExampleFile.com,1972-08-27T04:33:52+0000,20554
9,261327,Candida Grant MD,dino.upton@hotmail.com,+1.832.895.5915,"7084 Harber Hill Apt. 405 North Joannie, PA 52515","Gorczany, DuBuque and Aufderhar",https://examplefile.com,Sample file from ExampleFile.com,2008-03-22T23:20:17+0000,64732

In [ ]:
pd.read_csv('data2.tsv', sep='\t')  # in this file there is no heading so we are not getting proper data so we have to give column name ourselves

,482197,Mrs. Crystel Kilback,stehr.ron@mitchell.org,(331) 883-0638,"26136 Rogahn Shores North Jeradchester, CO 41098-3466","Bednar, Parisian and Heathcote",https://examplefile.com,Sample file from ExampleFile.com,2022-09-06T23:49:30+0000,19400
0,483618,Edna Konopelski,justina85@hotmail.com,+1-915-716-6309,"31229 Pfeffer Coves Apt. 123 Maximechester, ND...",Okuneva-Greenfelder,https://examplefile.com,Sample file from ExampleFile.com,1988-09-07T12:28:15+0000,64541
1,169389,Evalyn Spinka,jermey68@cruickshank.com,478.519.0099,70676 Gilbert Ferry Suite 568 Lake Antonettest...,Carroll LLC,https://examplefile.com,Sample file from ExampleFile.com,2006-05-13T04:42:01+0000,17803
2,137571,Lula Conn,anabel.klein@hotmail.com,+18643331243,"67821 Dare Alley Apt. 382 South Meredithmouth,...",Armstrong LLC,https://examplefile.com,Sample file from ExampleFile.com,1995-12-30T23:33:48+0000,12670
3,883214,Benton Sanford IV,dmitchell@gmail.com,1-269-634-6153,"919 Jadyn Route Suite 681 Carminefort, VT 4697...",Funk Inc,https://examplefile.com,Sample file from ExampleFile.com,1998-08-14T21:54:21+0000,2764
4,71315,Dr. Immanuel Mayer,claud.russel@treutel.com,+1-512-514-6693,"9670 Mills Landing Gutkowskihaven, DE 82483","Bergnaum, Sipes and Hoeger",https://examplefile.com,Sample file from ExampleFile.com,1974-12-12T07:14:52+0000,48902
5,739940,Ms. Crystel Cummings,aankunding@hotmail.com,+1 (631) 903-5562,"33511 Christa Trail Lake Jada, KS 52270",Hagenes-Wilderman,https://examplefile.com,Sample file from ExampleFile.com,1987-09-09T01:04:12+0000,40513
6,425524,Ms. Monica Roberts,kristian42@batz.com,+1 (669) 438-4452,"65892 Octavia Circle Suite 792 Jacintostad, MI...",Hamill-Kemmer,https://examplefile.com,Sample file from ExampleFile.com,2020-03-29T22:47:12+0000,59996
7,637305,Elwin Langosh,sauer.mohamed@hotmail.com,240.954.5678,"838 Renner Crossing Apt. 510 East Archibald, I...","Rogahn, Bashirian and Schulist",https://examplefile.com,Sample file from ExampleFile.com,1972-08-27T04:33:52+0000,20554
8,261327,Candida Grant MD,dino.upton@hotmail.com,+1.832.895.5915,"7084 Harber Hill Apt. 405 North Joannie, PA 52515","Gorczany, DuBuque and Aufderhar",https://examplefile.com,Sample file from ExampleFile.com,2008-03-22T23:20:17+0000,64732
9,961015,Lola Reinger,enrico.mertz@yahoo.com,+1 (682) 954-9155,"433 Brakus Junction Suite 519 North Garrett, S...","Hayes, Jacobs and Walker",https://examplefile.com,Sample file from ExampleFile.com,2008-02-16T19:16:08+0000,32080
10,75810,Dr. Mandy Doyle,carter.rose@douglas.com,(424) 892-2958,"489 Clotilde Stream Suite 612 McKenziestad, IA...","Grimes, Haley and Ward",https://examplefile.com,Sample file from ExampleFile.com,2003-06-30T11:36:10+0000,88580

In [19]:
pd.read_csv('data2.tsv', sep='\t' , names=['id'	,'name'	,'email',	'phone'	,'address',	'company'	,'website'	,'description'	,'timestamp'	,'random_number'])

,id,name,email,phone,address,company,website,description,timestamp,random_number
0,482197,Mrs. Crystel Kilback,stehr.ron@mitchell.org,(331) 883-0638,"26136 Rogahn Shores North Jeradchester, CO 410...","Bednar, Parisian and Heathcote",https://examplefile.com,Sample file from ExampleFile.com,2022-09-06T23:49:30+0000,19400
1,483618,Edna Konopelski,justina85@hotmail.com,+1-915-716-6309,"31229 Pfeffer Coves Apt. 123 Maximechester, ND...",Okuneva-Greenfelder,https://examplefile.com,Sample file from ExampleFile.com,1988-09-07T12:28:15+0000,64541
2,169389,Evalyn Spinka,jermey68@cruickshank.com,478.519.0099,70676 Gilbert Ferry Suite 568 Lake Antonettest...,Carroll LLC,https://examplefile.com,Sample file from ExampleFile.com,2006-05-13T04:42:01+0000,17803
3,137571,Lula Conn,anabel.klein@hotmail.com,+18643331243,"67821 Dare Alley Apt. 382 South Meredithmouth,...",Armstrong LLC,https://examplefile.com,Sample file from ExampleFile.com,1995-12-30T23:33:48+0000,12670
4,883214,Benton Sanford IV,dmitchell@gmail.com,1-269-634-6153,"919 Jadyn Route Suite 681 Carminefort, VT 4697...",Funk Inc,https://examplefile.com,Sample file from ExampleFile.com,1998-08-14T21:54:21+0000,2764
5,71315,Dr. Immanuel Mayer,claud.russel@treutel.com,+1-512-514-6693,"9670 Mills Landing Gutkowskihaven, DE 82483","Bergnaum, Sipes and Hoeger",https://examplefile.com,Sample file from ExampleFile.com,1974-12-12T07:14:52+0000,48902
6,739940,Ms. Crystel Cummings,aankunding@hotmail.com,+1 (631) 903-5562,"33511 Christa Trail Lake Jada, KS 52270",Hagenes-Wilderman,https://examplefile.com,Sample file from ExampleFile.com,1987-09-09T01:04:12+0000,40513
7,425524,Ms. Monica Roberts,kristian42@batz.com,+1 (669) 438-4452,"65892 Octavia Circle Suite 792 Jacintostad, MI...",Hamill-Kemmer,https://examplefile.com,Sample file from ExampleFile.com,2020-03-29T22:47:12+0000,59996
8,637305,Elwin Langosh,sauer.mohamed@hotmail.com,240.954.5678,"838 Renner Crossing Apt. 510 East Archibald, I...","Rogahn, Bashirian and Schulist",https://examplefile.com,Sample file from ExampleFile.com,1972-08-27T04:33:52+0000,20554
9,261327,Candida Grant MD,dino.upton@hotmail.com,+1.832.895.5915,"7084 Harber Hill Apt. 405 North Joannie, PA 52515","Gorczany, DuBuque and Aufderhar",https://examplefile.com,Sample file from ExampleFile.com,2008-03-22T23:20:17+0000,64732
10,961015,Lola Reinger,enrico.mertz@yahoo.com,+1 (682) 954-9155,"433 Brakus Junction Suite 519 North Garrett, S...","Hayes, Jacobs and Walker",https://examplefile.com,Sample file from ExampleFile.com,2008-02-16T19:16:08+0000,32080
11,75810,Dr. Mandy Doyle,carter.rose@douglas.com,(424) 892-2958,"489 Clotilde Stream Suite 612 McKenziestad, IA...","Grimes, Haley and Ward",https://examplefile.com,Sample file from ExampleFile.com,2003-06-30T11:36:10+0000,88580

In [ ]:
# we are getting the extra id as we have already the id so we can make the id in file as the index id 

pd.read_csv('data1.tsv',sep='\t',index_col='id')

# now our default pandas index that get auto generated is replaced with our own id

,name,email,phone,address,company,website,description,timestamp,random_number
id,,,,,,,,,
482197,Mrs. Crystel Kilback,stehr.ron@mitchell.org,(331) 883-0638,"26136 Rogahn Shores North Jeradchester, CO 410...","Bednar, Parisian and Heathcote",https://examplefile.com,Sample file from ExampleFile.com,2022-09-06T23:49:30+0000,19400
483618,Edna Konopelski,justina85@hotmail.com,+1-915-716-6309,"31229 Pfeffer Coves Apt. 123 Maximechester, ND...",Okuneva-Greenfelder,https://examplefile.com,Sample file from ExampleFile.com,1988-09-07T12:28:15+0000,64541
169389,Evalyn Spinka,jermey68@cruickshank.com,478.519.0099,70676 Gilbert Ferry Suite 568 Lake Antonettest...,Carroll LLC,https://examplefile.com,Sample file from ExampleFile.com,2006-05-13T04:42:01+0000,17803
137571,Lula Conn,anabel.klein@hotmail.com,+18643331243,"67821 Dare Alley Apt. 382 South Meredithmouth,...",Armstrong LLC,https://examplefile.com,Sample file from ExampleFile.com,1995-12-30T23:33:48+0000,12670
883214,Benton Sanford IV,dmitchell@gmail.com,1-269-634-6153,"919 Jadyn Route Suite 681 Carminefort, VT 4697...",Funk Inc,https://examplefile.com,Sample file from ExampleFile.com,1998-08-14T21:54:21+0000,2764
71315,Dr. Immanuel Mayer,claud.russel@treutel.com,+1-512-514-6693,"9670 Mills Landing Gutkowskihaven, DE 82483","Bergnaum, Sipes and Hoeger",https://examplefile.com,Sample file from ExampleFile.com,1974-12-12T07:14:52+0000,48902
739940,Ms. Crystel Cummings,aankunding@hotmail.com,+1 (631) 903-5562,"33511 Christa Trail Lake Jada, KS 52270",Hagenes-Wilderman,https://examplefile.com,Sample file from ExampleFile.com,1987-09-09T01:04:12+0000,40513
425524,Ms. Monica Roberts,kristian42@batz.com,+1 (669) 438-4452,"65892 Octavia Circle Suite 792 Jacintostad, MI...",Hamill-Kemmer,https://examplefile.com,Sample file from ExampleFile.com,2020-03-29T22:47:12+0000,59996
637305,Elwin Langosh,sauer.mohamed@hotmail.com,240.954.5678,"838 Renner Crossing Apt. 510 East Archibald, I...","Rogahn, Bashirian and Schulist",https://examplefile.com,Sample file from ExampleFile.com,1972-08-27T04:33:52+0000,20554
261327,Candida Grant MD,dino.upton@hotmail.com,+1.832.895.5915,"7084 Harber Hill Apt. 405 North Joannie, PA 52515","Gorczany, DuBuque and Aufderhar",https://examplefile.com,Sample file from ExampleFile.com,2008-03-22T23:20:17+0000,64732

In [31]:
pd.read_csv('test.csv',header=0)

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60_89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
8,0,0.116951,27,0,46.000000,NaN,2,0,0,0,NaN
9,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0
10,0,0.644226,30,0,0.309476,2500.0,5,0,0,0,0.0
11,0,0.018798,51,0,0.531529,6501.0,7,0,2,0,2.0
12,0,0.010352,46,0,0.298354,12454.0,13,0,2,0,2.0
13,1,0.964673,40,3,0.382965,13700.0,9,3,1,1,2.0
14,0,0.019657,76,0,477.000000,0.0,6,0,1,0,0.0
15,0,0.548458,64,0,0.209892,11362.0,7,0,1,0,2.0

usecols parameter

In [33]:
pd.read_csv('test.csv',usecols=['SeriousDlqin2yrs'	,'RevolvingUtilizationOfUnsecuredLines',	'age'])

    SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age
0                  1                              0.766127   45
1                  0                              0.957151   40
2                  0                              0.658180   38
3                  0                              0.233810   30
4                  0                              0.907239   49
5                  0                              0.213179   74
6                  0                              0.305682   57
7                  0                              0.754464   39
8                  0                              0.116951   27
9                  0                              0.189169   57
10                 0                              0.644226   30
11                 0                              0.018798   51
12                 0                              0.010352   46
13                 1                              0.964673   40
14                 0                              0.019657   76
15                 0                              0.548458   64

Squeeze parameters

In [ ]:
# pd.read_csv('test.csv',usecols=['age'],squeeze=True)

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

Skiprows/nrows Parameters

In [ ]:
pd.read_csv('test.csv',skiprows=[0,1]) # skip the specifiend rows

    0  0.957151019  40  0.1  0.121876201     2600   4  0.2  0.3  0.4    1
0   0     0.658180  38    1     0.085113   3042.0   2    1    0    0  0.0
1   0     0.233810  30    0     0.036050   3300.0   5    0    0    0  0.0
2   0     0.907239  49    1     0.024926  63588.0   7    0    1    0  0.0
3   0     0.213179  74    0     0.375607   3500.0   3    0    1    0  1.0
4   0     0.305682  57    0  5710.000000      NaN   8    0    3    0  0.0
5   0     0.754464  39    0     0.209940   3500.0   8    0    0    0  0.0
6   0     0.116951  27    0    46.000000      NaN   2    0    0    0  NaN
7   0     0.189169  57    0     0.606291  23684.0   9    0    4    0  2.0
8   0     0.644226  30    0     0.309476   2500.0   5    0    0    0  0.0
9   0     0.018798  51    0     0.531529   6501.0   7    0    2    0  2.0
10  0     0.010352  46    0     0.298354  12454.0  13    0    2    0  2.0
11  1     0.964673  40    3     0.382965  13700.0   9    3    1    1  2.0
12  0     0.019657  76    0   477.000000      0.0   6    0    1    0  0.0
13  0     0.548458  64    0     0.209892  11362.0   7    0    1    0  2.0

In [ ]:
pd.read_csv('test.csv',nrows=10)  # defines how many rows to keep

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60_89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
8,0,0.116951,27,0,46.000000,NaN,2,0,0,0,NaN
9,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0

Encoding Parameter

In [ ]:
# sometime the encoding is not common utf 8 in such case we can find the encoding used or use the edittor to change the encoding 
pd.read_csv('zomato.csv',encoding='latin-1')

Skip bad lines :
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
Specifies what to do upon encountering a bad line (a line with too many fields). Allowed values are :

'error', raise an Exception when a bad line is encountered.
'warn', raise a warning when a bad line is encountered and skip that line.
'skip', skip bad lines without raising or warning when they are encountered.

In [44]:
pd.read_csv('bad.csv',on_bad_lines='skip')

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60_89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
8,0,0.116951,27,0,46.000000,NaN,2,0,0,0,NaN
9,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0
10,0,0.644226,30,0,0.309476,2500.0,5,0,0,0,0.0
11,0,0.018798,51,0,0.531529,6501.0,7,0,2,0,2.0
12,0,0.010352,46,0,0.298354,12454.0,13,0,2,0,2.0
13,1,0.964673,40,3,0.382965,13700.0,9,3,1,1,2.0
14,0,0.548458,64,0,0.209892,11362.0,7,0,1,0,2.0
15,0,0.061086,78,0,2058.000000,NaN,10,0,2,0,0.0

dtypes parameter

In [ ]:
pd.read_csv('bad.csv',on_bad_lines='skip').info() 
# here we have the float for the number of dependents which is not neccesary as it will just take more memory we can convert to int

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   SeriousDlqin2yrs                      16 non-null     int64
 1   RevolvingUtilizationOfUnsecuredLines  16 non-null     float64
 2   age                                   16 non-null     int64
 3   NumberOfTime30-59DaysPastDueNotWorse  16 non-null     int64
 4   DebtRatio                             16 non-null     float64
 5   MonthlyIncome                         13 non-null     float64
 6   NumberOfOpenCreditLinesAndLoans       16 non-null     int64
 7   NumberOfTimes90DaysLate               16 non-null     int64
 8   NumberRealEstateLoansOrLines          16 non-null     int64
 9   NumberOfTime60_89DaysPastDueNotWorse  16 non-null     int64
 10  NumberOfDependents                    15 non-null     float64
dtypes: float64(4), int64(7)
memory usage: 1.5 KB

In [ ]:
pd.read_csv('bad.csv',on_bad_lines='skip',dtype={'NumberOfDependents':int}).info()

# now it will converted to integer type

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   SeriousDlqin2yrs                      15 non-null     int64
 1   RevolvingUtilizationOfUnsecuredLines  15 non-null     float64
 2   age                                   15 non-null     int64
 3   NumberOfTime30-59DaysPastDueNotWorse  15 non-null     int64
 4   DebtRatio                             15 non-null     float64
 5   MonthlyIncome                         13 non-null     float64
 6   NumberOfOpenCreditLinesAndLoans       15 non-null     int64
 7   NumberOfTimes90DaysLate               15 non-null     int64
 8   NumberRealEstateLoansOrLines          15 non-null     int64
 9   NumberOfTime60_89DaysPastDueNotWorse  15 non-null     int64
 10  NumberOfDependents                    15 non-null     int64
dtypes: float64(3), int64(8)
memory usage: 1.4 KB

Handling Dates 

parse_dates : bool, list of Hashable, list of lists or dict of {Hashable
The behavior is as follows:

bool. If True -> try parsing the index. Note: Automatically set to True if date_format or date_parser arguments have been passed.
list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3 each as a separate date column.
list of list. e.g. If [[1, 3]] -> combine columns 1 and 3 and parse as a single date column. Values are joined with a space before parsing.
dict, e.g. {'foo' ⁠:⁠ [1, 3]} -> parse columns 1, 3 as date and call result 'foo'. Values are joined with a space before parsing.
If a column or index cannot be represented as an array of datetime, say because of an unparsable value or a mixture of timezones, the column or index will be returned unaltered as an object data type. For non-standard datetime parsing, use ~pandas.to_datetime after ~pandas.read_csv.

In [ ]:
pd.read_csv('withdate.csv').info() # so date becomes the string by default. We cannot parse them as date

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Month        144 non-null    str
 1   #Passengers  144 non-null    int64
dtypes: int64(1), str(1)
memory usage: 3.4 KB

In [ ]:
pd.read_csv('withdate.csv',parse_dates=['Month']).info() # now it becomes the datetime64 data type

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Month        144 non-null    datetime64[us]
 1   #Passengers  144 non-null    int64
dtypes: datetime64[us](1), int64(1)
memory usage: 2.4 KB

In [ ]:
pd.read_csv('withdate.csv')

       Month  #Passengers
0    1949-01          112
1    1949-02          118
2    1949-03          132
3    1949-04          129
4    1949-05          121
..       ...          ...
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

[144 rows x 2 columns]

In [57]:
def removemonth(date):
    d =date.split(sep='-')
    return d[0]
removemonth("1948-01")

'1948'

Convertors:

In [ ]:
pd.read_csv('withdate.csv',converters={'Month': removemonth})
# this can be very helpful if we want some custom transformation

    Month  #Passengers
0    1949          112
1    1949          118
2    1949          132
3    1949          129
4    1949          121
..    ...          ...
139  1960          606
140  1960          508
141  1960          461
142  1960          390
143  1960          432

[144 rows x 2 columns]

na_values parameter

In [61]:
# sometime data set has the - value instead of The NaN of any other senseless. So we can define which values to be considered NaN
pd.read_csv('data.csv').head(10)

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60_89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
8,0,0.116951,27,0,46.000000,NaN,2,0,0,0,NaN
9,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0

In [ ]:
pd.read_csv('data.csv',na_values=[4,7]).head(10) # here we have considere 4, 7 as the useless values so as we can see they are converted to NaN

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60_89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2.0,0.802982,9120.0,13.0,0.0,6.0,0.0,2.0
1,0,0.957151,40,0.0,0.121876,2600.0,NaN,0.0,0.0,0.0,1.0
2,0,0.658180,38,1.0,0.085113,3042.0,2.0,1.0,0.0,0.0,0.0
3,0,0.233810,30,0.0,0.036050,3300.0,5.0,0.0,0.0,0.0,0.0
4,0,0.907239,49,1.0,0.024926,63588.0,NaN,0.0,1.0,0.0,0.0
5,0,0.213179,74,0.0,0.375607,3500.0,3.0,0.0,1.0,0.0,1.0
6,0,0.305682,57,0.0,5710.000000,NaN,8.0,0.0,3.0,0.0,0.0
7,0,0.754464,39,0.0,0.209940,3500.0,8.0,0.0,0.0,0.0,0.0
8,0,0.116951,27,0.0,46.000000,NaN,2.0,0.0,0.0,0.0,NaN
9,0,0.189169,57,0.0,0.606291,23684.0,9.0,0.0,NaN,0.0,2.0

Loading a Huge Dataset in chunks

In [77]:
dfs = pd.read_csv('data.csv',chunksize=5000)
# now this is stored in the list of the dataframes

In [78]:
# we can use the loop  to use the each chunk 
for chunks in dfs:
    print(chunks.shape)
    print(chunks)

# print(type(dfs))

(5000, 11)
      SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
0                    1                              0.766127   45
1                    0                              0.957151   40
2                    0                              0.658180   38
3                    0                              0.233810   30
4                    0                              0.907239   49
...                ...                                   ...  ...
4995                 0                              0.516205   54
4996                 0                              0.153128   32
4997                 0                              0.413590   55
4998                 0                              0.273258   44
4999                 0                              0.100264   43

      NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                        2   0.802982         9120.0
1                                        0   0.121876         2600.0
2                                        1   0.085113         3042.0
3                                        0   0.036050         3300.0
4                                        1   0.024926        63588.0
...                                    ...        ...            ...
4995                                     1   0.274175         4456.0
4996                                     1   0.082167         5500.0
4997                                     0   1.205276         1212.0
4998                                     0   3.762905         1142.0
4999                                     0   0.458429         3908.0

      NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                                  13                        0
1                                   4                        0
2                                   2                        1
3                                   5                        0
4                                   7                        0
...                               ...                      ...
4995                                7                        0
4996                                6                        0
4997                                9                        0
4998                                5                        0
4999                               23                        0

      NumberRealEstateLoansOrLines  NumberOfTime60_89DaysPastDueNotWorse  \
0                                6                                     0
1                                0                                     0
2                                0                                     0
3                                0                                     0
4                                1                                     0
...                            ...                                   ...
4995                             0                                     0
4996                             0                                     0
4997                             1                                     0
4998                             2                                     0
4999                             0                                     0

      NumberOfDependents
0                    2.0
1                    1.0
2                    0.0
3                    0.0
4                    0.0
...                  ...
4995                 1.0
4996                 3.0
4997                 0.0
4998                 2.0
4999                 0.0

[5000 rows x 11 columns]
(5000, 11)
      SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
5000                 0                              0.105212   57
5001                 0                              0.902261   41
5002                 0                              0.634157   55
5003                 0                              0.010343   52
5004                 0                              1.000000   47
...                ...                                   ...  ...
9995                 0                              0.629741   32
9996                 0                              0.062614   62
9997                 0                              0.827427   50
9998                 0                              0.091174   77
9999                 0                              0.000000   55

      NumberOfTime30-59DaysPastDueNotWorse    DebtRatio  MonthlyIncome  \
5000                                     0  2270.000000            NaN
5001                                     0     0.629763         5825.0
5002                                     0     0.180896        12918.0
5003                                     0  2874.000000            NaN
5004                                     0     0.000000            NaN
...                                    ...          ...            ...
9995                                     0   338.000000            NaN
9996                                     0   745.000000            NaN
9997                                     0  1904.000000            NaN
9998                                     1     0.020636        10999.0
9999                                     0     0.147588        12500.0

      NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
5000                                5                        0
5001                               11                        0
5002                               16                        0
5003                               16                        0
5004                                4                        0
...                               ...                      ...
9995                                2                        0
9996                               10                        0
9997                                4                        0
9998                                9                        0
9999                               15                        0

      NumberRealEstateLoansOrLines  NumberOfTime60_89DaysPastDueNotWorse  \
5000                             1                                     0
5001                             4                                     0
5002                             0                                     0
5003                             2                                     0
5004                             0                                     0
...                            ...                                   ...
9995                             0                                     0
9996                             1                                     0
9997                             0                                     0
9998                             0                                     0
9999                             1                                     0

      NumberOfDependents
5000                 0.0
5001                 0.0
5002                 0.0
5003                 0.0
5004                 0.0
...                  ...
9995                 0.0
9996                 0.0
9997                 0.0
9998                 0.0
9999                 1.0

[5000 rows x 11 columns]
(5000, 11)
       SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
10000                 0                              0.028381   66
10001                 0                              0.931678   38
10002                 0                              0.025367   57
10003                 0                              0.073886   76
10004                 0                              0.064243   49
...                 ...                                   ...  ...
14995                 0                              0.051347   68
14996                 0                              0.044247   76
14997                 0                              0.014464   60
14998                 0                              0.057423   47
14999                 0                              0.389083   46

       NumberOfTime30-59DaysPastDueNotWorse    DebtRatio  MonthlyIncome  \
10000                                     0    65.000000            NaN
10001                                     0     0.117874         5700.0
10002                                     0     0.589367         4833.0
10003                                     0     0.249393         7000.0
10004                                     0     0.229766        14035.0
...                                     ...          ...            ...
14995                                     0     0.405181         4207.0
14996                                     0     0.338915         4000.0
14997                                     0     0.238159         9732.0
14998                                     0    96.000000            NaN
14999                                     0  3615.000000            NaN

       NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
10000                                9                        0
10001                                6                        0
10002                               16                        0
10003                                9                        0
10004                               15                        0
...                                ...                      ...
14995                               10                        0
14996                                6                        0
14997                               12                        0
14998                                5                        0
14999                                6                        0

       NumberRealEstateLoansOrLines  NumberOfTime60_89DaysPastDueNotWorse  \
10000                             0                                     0
10001                             0                                     0
10002                             1                                     0
10003                             1                                     0
10004                             2                                     0
...                             ...                                   ...
14995                             1                                     0
14996                             1                                     0
14997                             2                                     0
14998                             0                                     0
14999                             1                                     0

       NumberOfDependents
10000                 NaN
10001                 3.0
10002                 0.0
10003                 0.0
10004                 3.0
...                   ...
14995                 0.0
14996                 0.0
14997                 1.0
14998                 0.0
14999                 0.0

[5000 rows x 11 columns]
(5000, 11)
       SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
15000                 0                              0.362943   44
15001                 0                              0.000826   59
15002                 0                              1.000000   71
15003                 0                              0.243788   45
15004                 0                              0.000000   58
...                 ...                                   ...  ...
19995                 1                              0.652695   43
19996                 0                              0.928239   50
19997                 0                              0.071401   58
19998                 0                              0.494396   42
19999                 0                              0.215368   53

       NumberOfTime30-59DaysPastDueNotWorse    DebtRatio  MonthlyIncome  \
15000                                     0     0.443979         6916.0
15001                                     1     0.029549        13333.0
15002                                     0     2.628307          755.0
15003                                     2  2073.500000            1.0
15004                                     0     0.142112         2300.0
...                                     ...          ...            ...
19995                                     0     1.880861         1300.0
19996                                     4     0.299610         5900.0
19997                                     0     0.509324          857.0
19998                                     1     0.283905         3000.0
19999                                     0     0.079168         2500.0

       NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
15000                               10                        0
15001                                8                        0
15002                                3                        0
15003                               14                        0
15004                                7                        0
...                                ...                      ...
19995                                9                        0
19996                                7                        0
19997                                6                        0
19998                                9                        0
19999                                5                        0

       NumberRealEstateLoansOrLines  NumberOfTime60_89DaysPastDueNotWorse  \
15000                             1                                     0
15001                             0                                     0
15002                             2                                     0
15003                             2                                     0
15004                             0                                     0
...                             ...                                   ...
19995                             1                                     1
19996                             1                                     0
19997                             0                                     0
19998                             0                                     0
19999                             0                                     0

       NumberOfDependents
15000                 3.0
15001                 3.0
15002                 0.0
15003                 3.0
15004                 0.0
...                   ...
19995                 0.0
19996                 1.0
19997                 0.0
19998                 2.0
19999                 0.0

[5000 rows x 11 columns]
(5000, 11)
       SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
20000                 0                              0.948602   39
20001                 1                              0.885052   70
20002                 0                              1.000000   33
20003                 0                              0.000000   35
20004                 0                              1.000000   23
...                 ...                                   ...  ...
24995                 0                              0.376248   65
24996                 0                              0.165808   51
24997                 0                              0.047056   57
24998                 0                              0.257984   55
24999                 0                              0.503031   47

       NumberOfTime30-59DaysPastDueNotWorse    DebtRatio  MonthlyIncome  \
20000                                     0     0.454759        10200.0
20001                                     0     0.836776         3436.0
20002                                     0     1.043666         5083.0
20003                                     0     0.326150         4500.0
20004                                     0     0.123186         3100.0
...                                     ...          ...            ...
24995                                     0  2471.000000            NaN
24996                                     0     0.278066         7900.0
24997                                     0     0.100115         7800.0
24998                                     1  3058.000000            NaN
24999                                     0     0.629975         8366.0

       NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
20000                               10                        0
20001                               17                        0
20002                                8                        0
20003                                8                        0
20004                                1                        0
...                                ...                      ...
24995                               18                        0
24996                               13                        0
24997                                9                        0
24998                               10                        0
24999                               21                        0

       NumberRealEstateLoansOrLines  NumberOfTime60_89DaysPastDueNotWorse  \
20000                             2                                     0
20001                             1                                     0
20002                             2                                     0
20003                             1                                     0
20004                             0                                     0
...                             ...                                   ...
24995                             2                                     0
24996                             2                                     0
24997                             1                                     0
24998                             1                                     0
24999                             3                                     0

       NumberOfDependents
20000                 1.0
20001                 0.0
20002                 1.0
20003                 0.0
20004                 2.0
...                   ...
24995                 0.0
24996                 2.0
24997                 0.0
24998                 0.0
24999                 1.0

[5000 rows x 11 columns]
(5000, 11)
       SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
25000                 0                              0.313020   46
25001                 0                              0.000707   89
25002                 0                              0.747656   38
25003                 0                              0.354438   57
25004                 0                              0.009300   90
...                 ...                                   ...  ...
29995                 0                              0.019171   64
29996                 0                              0.013746   69
29997                 0                              0.404015   54
29998                 0                              0.439308   62
29999                 0                              0.000000   49

       NumberOfTime30-59DaysPastDueNotWorse   DebtRatio  MonthlyIncome  \
25000                                     0    0.454388         3474.0
25001                                     0    0.000204         4900.0
25002                                     1    0.499012         8600.0
25003                                     0    0.263316        15000.0
25004                                     0    0.002000         8000.0
...                                     ...         ...            ...
29995                                     0  954.000000            NaN
29996                                     0    0.002999         4000.0
29997                                     0    0.070419         7000.0
29998                                     0    0.468150         6200.0
29999                                     0    0.181213         5705.0
