In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
# df['cough'].value_counts()
df['city'].value_counts() # 4 cities

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

Gender and city is the nominal categorical Data : So we need to do the nominal encoding / one hot encoding 
Fever and cough is the ordinal categorical Data : So we need to do Ordinal encoding

Not doing the label encoding on the has_covid, and not doing the scalind too

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [10]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
37   55    Male  100.0    Mild    Kolkata
0    60    Male  103.0    Mild    Kolkata
73   34    Male   98.0  Strong    Kolkata
63   10    Male  100.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
25   23    Male    NaN    Mild     Mumbai
76   80    Male  100.0    Mild  Bangalore
51   11  Female  100.0  Strong    Kolkata
14   51    Male  104.0    Mild  Bangalore
4    65  Female  101.0    Mild     Mumbai

[80 rows x 5 columns]

### Without the Column transformer .

In [11]:

# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [15]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']]) # smaller to larger value
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape
# X_train_cough

(80, 1)

In [17]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)