In [5]:
import numpy as np
import pandas as pd

In [6]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [7]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [8]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [10]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

So we can see the Data and time is by default is object/ string so we cannot parse the info out of those

# Working with Dates

In [11]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [12]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [54]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

#### 1. Extract year

In [ ]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
991 2019-01-12        5780        0       2       2019
672 2019-09-18         779       16       1       2019
155 2019-03-04        3888        0       1       2019
946 2018-11-10        6309       29      11       2018
777 2018-12-23        3833       26     212       2018

#### 2. Extract Month

In [14]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [15]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

#### Extract Days

In [16]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [17]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [18]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [19]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

#### Extract week of the year

In [30]:
# date['date_week'] = date['date'].dt.week # Deprecated
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

#### Extract Quarter

In [25]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1

#### Extract Semester

In [26]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1,1

#### Extract Time elapsed between dates

In [27]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 16, 14, 48, 11, 923294)

In [28]:
today - date['date']

0     2410 days 14:48:11.923294
1     2892 days 14:48:11.923294
2     2823 days 14:48:11.923294
3     2525 days 14:48:11.923294
4     2748 days 14:48:11.923294
                 ...
995   2838 days 14:48:11.923294
996   2779 days 14:48:11.923294
997   2627 days 14:48:11.923294
998   2692 days 14:48:11.923294
999   2466 days 14:48:11.923294
Name: date, Length: 1000, dtype: timedelta64[ns]

In [29]:
(today - date['date']).dt.days

0      2410
1      2892
2      2823
3      2525
4      2748
       ...
995    2838
996    2779
997    2627
998    2692
999    2466
Name: date, Length: 1000, dtype: int64

In [62]:
# Months passed

# np.round((today -date['date']) / np.timedelta64(1, 'M'),0)
# np.round((today -date['date']) / 30,0)

Deprecated modern better way is:

In [60]:
today = pd.Timestamp.today()

date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12
    + (today.month - date['date'].dt.month)
)

In [61]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2,79
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2,95
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2,93
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2,83
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1,90

## Time

In [48]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [49]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [50]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [51]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

#### Extract Time part

In [52]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

#### Time difference

In [55]:
today - time['date']

0     4596 days 13:58:11.923294
1     4460 days 15:08:11.923294
2     4946 days 14:27:11.923294
3     4248 days 14:17:11.923294
4     4645 days 15:37:11.923294
                 ...
995   5235 days 13:58:11.923294
996   4556 days 15:34:11.923294
997   5021 days 15:11:11.923294
998   5137 days 15:14:11.923294
999   4409 days 15:23:11.923294
Name: date, Length: 1000, dtype: timedelta64[ns]

In [56]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.971447e+08
1      3.853985e+08
2      4.273864e+08
3      3.670786e+08
4      4.013842e+08
           ...
995    4.523543e+08
996    3.936945e+08
997    4.338691e+08
998    4.438917e+08
999    3.809930e+08
Name: date, Length: 1000, dtype: float64

In [57]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.619078e+06
1      6.423308e+06
2      7.123107e+06
3      6.117977e+06
4      6.689737e+06
           ...
995    7.539238e+06
996    6.561574e+06
997    7.231151e+06
998    7.398194e+06
999    6.349883e+06
Name: date, Length: 1000, dtype: float64

In [58]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      110317.969979
1      107055.136645
2      118718.453312
3      101966.286645
4      111495.619979
           ...
995    125653.969979
996    109359.569979
997    120519.186645
998    123303.236645
999    105831.386645
Name: date, Length: 1000, dtype: float64